name: 'AWS CodeGuru Security Action'
description: 'AWS CodeGuru Security Action'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  source_path:
    description: 'Path to source repository'
    default: .
    required: false
  aws_region:
    description: 'AWS region where you want to run workflow'
    required: true
runs:
  using: docker
  image: docker://codeguru:latest
  args:
   - --source_path
   - ${{ inputs.source_path }}
   - --aws_region
   - ${{ inputs.aws_region }}
   - --output_file
   - codeguru-security-results
